"""Run the access-control test matrix and write the security test report.

    python -m scripts.matrix_report             runs tests/test_access_matrix.py, writes
                                                docs/test-report.md and reports/access-matrix.json

The report is built from the test results themselves (pytest's JUnit XML), not from the
expected values: a failing cell shows as FAIL, and a check that did not run (for example
without a database) shows as SKIPPED and is never counted as passed.
"""

import json
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from collections import defaultdict
from pathlib import Path

from tests.test_access_matrix import BAD, MEMBERSHIPS, PEOPLE, ROUTES, expected

ROOT = Path(__file__).resolve().parent.parent
NAMES = {
    "usr-grace": "Grace",
    "usr-sam": "Sam",
    "usr-omar": "Omar",
    "usr-ines": "Ines",
    "usr-camille": "Camille",
    "usr-tomas": "Tomás",
    "usr-kwame": "Kwame",
}


def run_tests() -> dict[str, dict[str, str]]:
    with tempfile.TemporaryDirectory() as tmp:
        xml = Path(tmp) / "matrix.xml"
        subprocess.run(
            [
                sys.executable,
                "-m",
                "pytest",
                "-q",
                "-p",
                "no:cacheprovider",
                "tests/test_access_matrix.py",
                f"--junitxml={xml}",
            ],
            cwd=ROOT,
            capture_output=True,
            text=True,
        )
        results = defaultdict(dict)
        for case in ET.parse(xml).getroot().iter("testcase"):
            name = case.get("name")
            test, params = name.split("[", 1)
            if case.find("failure") is not None or case.find("error") is not None:
                outcome = "FAIL"
            elif case.find("skipped") is not None:  # not run (no database): never a pass
                outcome = "SKIPPED"
            else:
                outcome = "pass"
            results[test][params.rstrip("]")] = outcome
    return results


def main() -> int:
    results = run_tests()
    matrix = results.get("test_matrix", {})
    rows, out = [], []
    for user in PEOPLE:
        for tenant in ("larkfield", "bramble"):
            role = MEMBERSHIPS.get((tenant, user), "none")
            cells = []
            for route in ROUTES:
                want = expected(user, tenant, route)
                outcome = matrix.get(f"{user}|{tenant}|{route}", "missing")
                cells.append({"route": route, "expected": want, "outcome": outcome})
            rows.append(
                {"user": user, "name": NAMES[user], "tenant": tenant, "role": role, "cells": cells}
            )
    passed = sum(v == "pass" for r in results.values() for v in r.values())
    total = sum(len(r) for r in results.values())
    report = {
        "passed": passed,
        "total": total,
        "rows": rows,
        "bola": results.get("test_another_organizations_record_id", {}),
        "bad_identity": results.get("test_bad_identity", {}),
    }
    (ROOT / "reports").mkdir(exist_ok=True)
    (ROOT / "reports" / "access-matrix.json").write_text(json.dumps(report, indent=2) + "\n")

    out.append("# Security test report: access control\n")
    out.append(
        f"**{passed} of {total} checks passed.** Generated by `python -m scripts.matrix_report`"
        " from the results of `tests/test_access_matrix.py` (made-up people and data).\n"
    )
    out.append("## Person x organization x route\n")
    out.append(
        "Each cell is the HTTP status the access matrix requires; **FAIL** marks a cell "
        "where the API answered something else. 404 = not a member (nothing is "
        "revealed), 403 = a member whose role may not do it.\n"
    )
    out.append("| Person | Organization | Role | " + " | ".join(ROUTES) + " |")
    out.append("|---" * (3 + len(ROUTES)) + "|")
    for r in rows:
        cells = [
            f"{c['expected']}" + ("" if c["outcome"] == "pass" else f" **{c['outcome']}**")
            for c in r["cells"]
        ]
        out.append(f"| {r['name']} | {r['tenant']} | {r['role']} | " + " | ".join(cells) + " |")
    out.append("\n## Another organization's record ID (object-level access)\n")
    for k, v in report["bola"].items():
        out.append(f"- {k.replace('|', ', ')}: {v}")
    out.append("\n## Bad identities on every route\n")
    for kind in BAD:
        cases = {k: v for k, v in report["bad_identity"].items() if k.startswith(kind + "|")}
        ok = sum(v == "pass" for v in cases.values())
        want = "403" if kind == "no scope" else "401"
        out.append(f"- {kind}: {ok} of {len(cases)} routes answered {want}")
    (ROOT / "docs" / "test-report.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    skipped = sum(v == "SKIPPED" for r in results.values() for v in r.values())
    print(
        f"{passed} of {total} checks passed. Wrote docs/test-report.md and"
        " reports/access-matrix.json."
    )
    if skipped:
        print(f"{skipped} checks did not run (skipped). Is PostgreSQL running?")
    return 0 if passed == total else 1


if __name__ == "__main__":
    sys.exit(main())
