-- The help desk's own data, as it came out of the old help-desk tool: one table
-- per kind of record, each with a primary key, and nothing else yet. Module 2 of
-- the databases course adds the rules (constraints) that keep the data correct.
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE customers (
    customer_id text PRIMARY KEY,
    name        text,
    email       text,
    segment     text,
    region      text,
    joined_on   date,
    created_at  timestamptz
);

CREATE TABLE tickets (
    ticket_id   text PRIMARY KEY,
    customer_id text,
    subject     text,
    body        text,
    channel     text,
    team        text,
    priority    smallint,
    status      text,
    created_at  timestamptz,
    updated_at  timestamptz,
    closed_at   timestamptz
);

CREATE TABLE messages (
    message_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id  text,
    author     text,
    body       text,
    created_at timestamptz
);

-- The files themselves are not in the database: only their details.
CREATE TABLE attachments (
    attachment_id uuid PRIMARY KEY,
    ticket_id     text,
    file_name     text,
    content_type  text,
    size_bytes    bigint,
    sha256        text,
    object_key    text,
    uploaded_at   timestamptz
);

CREATE TABLE documents (
    doc_id         text,
    version        integer,
    title          text,
    doc_type       text,
    language       text,
    access         text,
    effective_from date,
    effective_to   date,
    body           text,
    sha256         text,
    PRIMARY KEY (doc_id, version)
);

-- One row per call to a model: which model and prompt, tokens, cost, time, result.
CREATE TABLE ai_runs (
    run_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id      text,
    task           text,
    model          text,
    prompt_version text,
    tokens_in      integer,
    tokens_out     integer,
    cost_usd       real,
    latency_ms     integer,
    status         text,
    output         text,
    created_at     timestamptz
);

-- A vector for each ticket, for finding similar tickets. Made from the
-- ticket's text by an embedding model: a copy that can be made again.
CREATE TABLE ticket_embeddings (
    ticket_id text PRIMARY KEY,
    embedding vector(384)
);
